package com.edu.agent.core;

public enum EventType {
    STUDENT_SUBMISSION,
    STUDENT_QUESTION,
    STUDENT_MESSAGE,
    ASSESSMENT_COMPLETE,
    MASTERY_UPDATED,
    WEAKNESS_DETECTED,
    TEACHING_RESPONSE,
    HINT_NEEDED,
    DIFFICULTY_ADJUSTED,
    PATH_UPDATED,
    REVIEW_SCHEDULED,
    NEXT_TOPIC,
    HINT_RESPONSE,
    ENGAGEMENT_ALERT,
    ENCOURAGEMENT,
    PACE_ADJUSTMENT
}
